// "metadata" and "generateMetadata" are conventions
// page metadata is prioritized over layout metadata 
// layout is like components inside a component -> nesting possible
//check about route metadata

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header>Header</header>
        {children}
        <footer>Footer</footer>
      </body>
      
    </html>
  )
}
