// "metadata" and "generateMetadata" are conventions
// page metadata is prioritized over layout metadata 
// layout is like a parent component in which page.tsx & other child components will come -> nesting possible
//check about, folder/route metadata
//template key in title object of metadata is only for child components
//root layout.tsx is must and can't be replaced with template.jsx


import { Metadata } from "next"
import './globals.css'


export const metadata: Metadata = {
  title: {
    absolute:"",
    default:"default title",
    template:"%s | Next.js",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      
      <body>
        <header>Header</header>
        {children}
        <footer>Footer</footer>
      </body>
      
    </html>
  )
}
